default:
  image: node:14.17-alpine3.11

build-job:
  stage: build
  script:
    - npm install

publish:
  stage: deploy
  before_script:
    - npm install --save-dev @babel/core @babel/cli
  script:
    - mkdir dist
    - npm run prepare-publish
    - npm publish
