default:
  image: maven:3.8.1-jdk-11

build-job:
  stage: build
  script:
    - npm install

publish:
  stage: deploy
  only:
    - tags
  script:
    - npm version ${CI_COMMIT_TAG}
    - git push
    - npm publish --access public
