default:
  image: node:14.17-alpine3.11

build-job:
  stage: build
  script:
    - npm install

publish:
  stage: deploy
  script:
    - npm install --global rollup
    - npm run prepare-publish
    - npm publish
