default:
  image: node:latest

build-job:
  stage: build
  script:
    - npm install

publish:
  stage: deploy
  only:
    - tags
  script:
    - npm version ${CI_COMMIT_TAG}
    - git push
    - npm publish --access public
