default:
  image: node:16-alpine

build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
    - npm run test

publish:
  stage: deploy
  script:
    - npm run prepare-publish
    - npm publish
