default:
  image: node:14.17-alpine3.11

build-job:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

publish:
  stage: deploy
  script:
    - npm run prepare-publish
    - npm publish
